project_dir: "/mnt/d/image-stitcher/"
input_dir: "/mnt/d/datasets/isdc_test_drone_datasets/d1"
stitch_dir: /mnt/d/image-stitcher/stitched/stitched
input_limit: null # Set to None if all input images should be considered

mode: 0 # 0: affine, 1: perspective
consecutive_range: 2 # Set to None if all should be checked
min_match_threshold: 20
lowes_ratio: 0.6