project_dir: "/mnt/d/image-stitcher/"
input_dir: "/mnt/d/datasets/isdc_test_drone_datasets/d1"
stitch_dir: /mnt/d/image-stitcher/stitched/stitched28
input_limit: null # Set to null if all input images should be considered

resize: null # Set to null for no resizing
algorithm: 1 # 0: SIFT, 1: ORB, 2: AKAZE
matcher: 1 # 0: BruteForce, 1: FlannBased
type: 0 # 0: affine, 1: perspective

min_match_threshold: 5
lowes_ratio: 0.65
# ref_image_contrib: null # Set to null for default

arbitrary: false
consecutive_range: 2 # Set to null if all should be checked

loglevel: 2 # 0: Nothing 1: DEBUG, 2: INFO, 3: WARNING
