project_dir: "/mnt/d/image-stitcher/"
input_dir: "/mnt/d/datasets/isdc_test_drone_datasets/d1"
stitch_dir: /mnt/d/image-stitcher/stitched/stitched12
input_limit: null # Set to null if all input images should be considered

resize: null # Set to null for no resizing
algorithm: 2 # 0: SIFT, 1: ORB, 2: AKAZE, 3. SURF
matcher: 1 # 0: BruteForce, 1: FlannBased
type: 0 # 0: affine, 1: perspective
consecutive_range: 2 # Set to null if all should be checked
min_match_threshold: 5
lowes_ratio: 0.65